

Automatic Doors Import

How to use Automatic Doors import:

1)	Install Python 2.7 from the path \\bosch.com\DfsRB\DfsIN\LOC\Kor\NE1\NE1_GS_SDE\tme_ext\ssb2cob\python2.7
2)	Execute the python file ‘AutomaticDoorsImport.py’ for normal files and Automatic_DoorsImport_CDeployment.py for C deployment modified files.
  
3)	Choose the test file ‘c’ or ‘cpp’ for which Testcases need to be imported into doors by scrolling down the button shown below,
 

4)	Please check for ‘Error’ in the CMD log to check any Expected call Function which cannot be extracted by the script.
5)	The result CSV files will be stored in the location C:/Doors/test_folder
Note: Single CSV file will be created for all the test functions for a specific SUT function.











Note: For the tool to work properly,
1) Please do not put any commented lines inside run_tests() and Expected_calls() functions.
2) For a SUT function computeRefinedCam2CamMotion() , the test case name should be as test_computeRefinedCam2CamMotion_1, test_computeRefinedCam2CamMotion_2 to test_computeRefinedCam2CamMotion_n in order. For a single testcase functions, test_computeRefinedCam2CamMotion is acceptable. 

CORRECT FORMAT: 
 
 















INCORRECT FORMAT:

 
 
























How to import created CSV file into Doors:

1)  In the SRVC,SVS template, give details till the SUT function name (Marked in the box in below picture.)
 
2) By keeping the cursor on Test Case_1, fileImport Spreadsheet
 

3) A box will appear as below, Keep the default setting as below and  browse the exact CSV file generated by script for specific SUT function, Click import
  



4) After selecting Import, A ‘Select Key’ box will appear, Keep the default setting ‘Object Text’ and click select, All the test cases related to SUT function will be imported automatically.
 

5) Please find the screenshot of imported tests and test attributes filled automatically.
 
